version: '2.3'
services:
  couchdb:
    build: ./db
    environment:
      - COUCHDB_USER=admin
      # dont rely on this password, it changed in server
      - COUCHDB_PASSWORD=password
    networks:
      internal:
        ipv4_address: 172.30.1.3
  web:
    build: ./web
    environment:
      - FLAG=fakeflag{shiki_natsume_1s_my_w41fu!!!!!}
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    depends_on:
      - couchdb
    ports:
      - "33000:3000"
    extra_hosts:
      - "cross-domain-iframe.com:127.0.0.1"
    networks:
      internal:
        ipv4_address: 172.30.1.2
      external:
networks:
  internal:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
  external:
    ipam:
      driver: default
