#!/bin/sh
#
#    00-header - create the header of the MOTD
#    Copyright (C) 2009-2010 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.comBH\HY\[H\HYH[YX\NH[]HX[Y\]X]H][[\[YYBH][\H\\HYHSHY[\[XXHXY[YH\HX\ZYBHHYH[YX\H][][[HZ]\\Z[[YHXY[YK\H
][]\\[[
H[H]\\Z[[BH\HY\[H\H\]X]Y[H\H]]Z[H\YY[H]RUUUSHPTSNHZ]]]][H[\YYX\[HYHQTRSPSUH\UTTHTHTPUSTTTQKYYHBHSHY[\[XXHXY[YH\[\H]Z[KBH[]HZ][]HXYZ]YH[\HYHSHY[\[XXHXY[YH[[BHZ]\HY\[NHY]\]HHHYH[YX\H][][[[KHLH[[[]Y]Y[\\][PHLLLLLHTPKH\Y]K[X\[X\YHH		Y]K[X\[X\YBYH^	TUPQTPTTSSH		H^]\\X[[X\[X\YHNH[HH[XZHH\Z[HH\H[]HX\[X\YH][]BQTUPQTPTTSSI
X\[X\YH\HY
BB[Y[[[YHH	\H
	\H	\H	\JW	TUPQTPTTSS	
[[YH[JH	
[[YH\
H	
[[YH[JH